name: dev branch ci

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Post to a Slack channel
        # id: slack_send
        uses: "./.github/actions/customslack"
        with:
          mode: PR
          channelId: "${{ secrets.CHANNEL_ID }}"
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
